# Generated by carnix 0.6.6: carnix -o dwm-status.nix --src ./. Cargo.lock --standalone
with import <nixpkgs> {};
let kernel = buildPlatform.parsed.kernel.name;
    abi = buildPlatform.parsed.abi.name;
    include = includedFiles: src: builtins.filterSource (path: type:
      lib.lists.any (f:
        let p = toString (src + ("/" + f)); in
        (path == p) || (type == "directory" && lib.strings.hasPrefix path p)
      ) includedFiles
    ) src;
    updateFeatures = f: up: functions: builtins.deepSeq f (lib.lists.foldl' (features: fun: fun features) (lib.attrsets.recursiveUpdate f up) functions);
    mapFeatures = features: map (fun: fun { features = features; });
    mkFeatures = feat: lib.lists.foldl (features: featureName:
      if feat.${featureName} or false then
        [ featureName ] ++ features
      else
        features
    ) [] (builtins.attrNames feat);
in
rec {
  dwm_status = f: dwm_status_0_3_1 { features = dwm_status_0_3_1_features { dwm_status_0_3_1 = f; }; };
  aho_corasick_0_6_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "aho-corasick";
    version = "0.6.4";
    authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
    sha256 = "189v919mp6rzzgjp1khpn4zlq8ls81gh43x1lmc8kbkagdlpq888";
    libName = "aho_corasick";
    crateBin = [ {  name = "aho-corasick-dot"; } ];
    inherit dependencies buildDependencies features;
  };
  bitflags_0_9_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "bitflags";
    version = "0.9.1";
    authors = [ "The Rust Project Developers" ];
    sha256 = "18h073l5jd88rx4qdr95fjddr9rk79pb1aqnshzdnw16cfmb9rws";
    inherit dependencies buildDependencies features;
  };
  bitflags_1_0_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "bitflags";
    version = "1.0.1";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0p4b3nr0s5nda2qmm7xdhnvh4lkqk3xd8l9ffmwbvqw137vx7mj1";
    inherit dependencies buildDependencies features;
  };
  cfg_if_0_1_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "cfg-if";
    version = "0.1.2";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "0x06hvrrqy96m97593823vvxcgvjaxckghwyy2jcyc8qc7c6cyhi";
    inherit dependencies buildDependencies features;
  };
  chrono_0_4_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "chrono";
    version = "0.4.2";
    authors = [ "Kang Seonghoon <public+rust@mearie.org>" "Brandon W Maister <quodlibetor@gmail.com>" ];
    sha256 = "1zp63v1g56kfjnazmqg8s4gb66l0ra8ggn3gzqbf9sr8d5lnfzak";
    inherit dependencies buildDependencies features;
  };
  clippy_0_0_194_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "clippy";
    version = "0.0.194";
    authors = [ "Manish Goregaokar <manishsmail@gmail.com>" "Andre Bogus <bogusandre@gmail.com>" "Georg Brandl <georg@python.org>" "Martin Carton <cartonmartin@gmail.com>" "Oliver Schneider <clippy-iethah7aipeen8neex1a@oli-obk.de>" ];
    sha256 = "1gpkma3hc8s7kksq7s9941drrp3j679y45dpkf1mxinxlx8imi0f";
    plugin = true;
    crateBin = [ {  name = "cargo-clippy";  path = "src/main.rs"; } {  name = "clippy-driver";  path = "src/driver.rs"; } ];
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  clippy_lints_0_0_194_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "clippy_lints";
    version = "0.0.194";
    authors = [ "Manish Goregaokar <manishsmail@gmail.com>" "Andre Bogus <bogusandre@gmail.com>" "Georg Brandl <georg@python.org>" "Martin Carton <cartonmartin@gmail.com>" ];
    sha256 = "1kiy774b3bg9drkbvf0xjdsy7sfid175wcsl939lykpirydy2s6g";
    inherit dependencies buildDependencies features;
  };
  dbus_0_6_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "dbus";
    version = "0.6.1";
    authors = [ "David Henningsson <diwic@ubuntu.com>" ];
    sha256 = "0291ggzs92gzag7gcxpqi8n7mnrlwszizwcrqky8v7sak16kbj1f";
    inherit dependencies buildDependencies features;
  };
  dwm_status_0_3_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "dwm-status";
    version = "0.3.1";
    authors = [ "Tobias Happ <tobias.happ@gmx.de>" ];
    src = ./.;
    inherit dependencies buildDependencies features;
  };
  either_1_5_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "either";
    version = "1.5.0";
    authors = [ "bluss" ];
    sha256 = "1f7kl2ln01y02m8fpd2zrdjiwqmgfvl9nxxrfry3k19d1gd2bsvz";
    inherit dependencies buildDependencies features;
  };
  fuchsia_zircon_0_3_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "fuchsia-zircon";
    version = "0.3.3";
    authors = [ "Raph Levien <raph@google.com>" ];
    sha256 = "0jrf4shb1699r4la8z358vri8318w4mdi6qzfqy30p2ymjlca4gk";
    inherit dependencies buildDependencies features;
  };
  fuchsia_zircon_sys_0_3_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "fuchsia-zircon-sys";
    version = "0.3.3";
    authors = [ "Raph Levien <raph@google.com>" ];
    sha256 = "08jp1zxrm9jbrr6l26bjal4dbm8bxfy57ickdgibsqxr1n9j3hf5";
    inherit dependencies buildDependencies features;
  };
  futures_0_1_21_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "futures";
    version = "0.1.21";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "0v4xrgkqx189b3b4lad2z5l9ay261p9412bzcdh1z6agxwhldr40";
    inherit dependencies buildDependencies features;
  };
  gdk_pixbuf_0_3_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gdk-pixbuf";
    version = "0.3.0";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "0jd4l0avnp6m5k7y8f5b46i9gsmrwgk1azz7brhkhkjjnxy2zhfj";
    libName = "gdk_pixbuf";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  gdk_pixbuf_sys_0_5_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gdk-pixbuf-sys";
    version = "0.5.0";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "0j1isix7m2g3dbs19zlm5ar504i30yip5bwcg0b6gdpalhyjcg7c";
    libName = "gdk_pixbuf_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  getopts_0_2_17_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "getopts";
    version = "0.2.17";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1rifkxn7njr2w1dsa29hrm26ywgcg8gv1ms00g3vs5mjiabxk0jv";
    inherit dependencies buildDependencies features;
  };
  gio_sys_0_5_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gio-sys";
    version = "0.5.0";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "0bym5n5lmlnsgc26a0n0faaj1w7nh3g1qxcsk5z9qnng5sm9gcyc";
    libName = "gio_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  glib_0_4_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "glib";
    version = "0.4.1";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "1sg6pj535274jym5sayfk0y6ba4lf5mhcfi6fzsl8bhlna514qii";
    inherit dependencies buildDependencies features;
  };
  glib_sys_0_5_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "glib-sys";
    version = "0.5.0";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "1i0kiylxrcs20crq5rm9lrv2q8pynqj9hk4cir3mg2qmrgmp7ign";
    libName = "glib_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  gobject_sys_0_5_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "gobject-sys";
    version = "0.5.0";
    authors = [ "The Gtk-rs Project Developers" ];
    sha256 = "08hraq27q8gb3x6h67xbxhkpwm2bxhh23i2fi02953c8i9kjj242";
    libName = "gobject_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  idna_0_1_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "idna";
    version = "0.1.4";
    authors = [ "The rust-url developers" ];
    sha256 = "15j44qgjx1skwg9i7f4cm36ni4n99b1ayx23yxx7axxcw8vjf336";
    inherit dependencies buildDependencies features;
  };
  if_chain_0_1_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "if_chain";
    version = "0.1.2";
    authors = [ "Chris Wong <lambda.fairy@gmail.com>" ];
    sha256 = "11iymajpmzbzrm80zrilyip9k7iylpjf57p8d699dgp75slg4g38";
    inherit dependencies buildDependencies features;
  };
  inotify_0_5_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "inotify";
    version = "0.5.1";
    authors = [ "Hanno Braun <mail@hannobraun.de>" "Félix Saparelli <me@passcod.name>" "Cristian Kubis <cristian.kubis@tsunix.de>" "Frank Denis <github@pureftpd.org>" ];
    sha256 = "08l1q116cfcv8qiavsbkcc5c2fyfd1w7a9fn17hb7phhnj3ab5nq";
    inherit dependencies buildDependencies features;
  };
  inotify_sys_0_1_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "inotify-sys";
    version = "0.1.2";
    authors = [ "Hanno Braun <hb@hannobraun.de>" ];
    sha256 = "157f9smnbwx1dy1nm7vfmsnxglpgbx0havb048szkq39cxby8y77";
    inherit dependencies buildDependencies features;
  };
  itertools_0_7_8_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "itertools";
    version = "0.7.8";
    authors = [ "bluss" ];
    sha256 = "0ib30cd7d1icjxsa13mji1gry3grp72kx8p33yd84mphdbc3d357";
    inherit dependencies buildDependencies features;
  };
  lazy_static_1_0_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "lazy_static";
    version = "1.0.0";
    authors = [ "Marvin Löbel <loebel.marvin@gmail.com>" ];
    sha256 = "0wfvqyr2nvx2mbsrscg5y7gfa9skhb8p72ayanl8vl49pw24v4fh";
    inherit dependencies buildDependencies features;
  };
  libc_0_2_40_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "libc";
    version = "0.2.40";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1xfc39237ldzgr8x8wcflgdr8zssi3wif7g2zxc02d94gzkjsw83";
    inherit dependencies buildDependencies features;
  };
  libdbus_sys_0_1_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "libdbus-sys";
    version = "0.1.3";
    authors = [ "David Henningsson <diwic@ubuntu.com>" ];
    sha256 = "1ydlmz9i9n685g5p899rpjz1ml91h2mbxz2qymjv7cjq4hxyk11y";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  libnotify_1_0_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "libnotify";
    version = "1.0.3";
    authors = [ "Mika Attila <radiantstatue@gmail.com>" "Julian Ospald <hasufell@posteo.de>" ];
    sha256 = "0k1c1kagrbl1nw14hzsgm33cmssmgxg929gfr4j2fsjxarmx0w3y";
    inherit dependencies buildDependencies features;
  };
  libnotify_sys_1_0_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "libnotify-sys";
    version = "1.0.2";
    authors = [ "Mika Attila <radiantstatue@gmail.com>" "Julian Ospald <hasufell@posteo.de>" ];
    sha256 = "1hazjmxc18s40li1d95kgcafgr3xial483jv24igc98p4cmawrnc";
    libName = "libnotify_sys";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  matches_0_1_6_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "matches";
    version = "0.1.6";
    authors = [ "Simon Sapin <simon.sapin@exyr.org>" ];
    sha256 = "1zlrqlbvzxdil8z8ial2ihvxjwvlvg3g8dr0lcdpsjclkclasjan";
    libPath = "lib.rs";
    inherit dependencies buildDependencies features;
  };
  memchr_2_0_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "memchr";
    version = "2.0.1";
    authors = [ "Andrew Gallant <jamslam@gmail.com>" "bluss" ];
    sha256 = "0ls2y47rjwapjdax6bp974gdp06ggm1v8d1h69wyydmh1nhgm5gr";
    inherit dependencies buildDependencies features;
  };
  num_integer_0_1_36_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "num-integer";
    version = "0.1.36";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1fjprz9h8b04zrsnfmkkfhiw4w852bbh16hy8w9ahlcdhg77i66y";
    inherit dependencies buildDependencies features;
  };
  num_traits_0_2_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "num-traits";
    version = "0.2.2";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1gcqhcd27gi72al5salxlp3m374qr3xnc3zh249f7dsrxc9rmgh0";
    inherit dependencies buildDependencies features;
  };
  percent_encoding_1_0_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "percent-encoding";
    version = "1.0.1";
    authors = [ "The rust-url developers" ];
    sha256 = "04ahrp7aw4ip7fmadb0bknybmkfav0kk0gw4ps3ydq5w6hr0ib5i";
    libPath = "lib.rs";
    inherit dependencies buildDependencies features;
  };
  pkg_config_0_3_9_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "pkg-config";
    version = "0.3.9";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "06k8fxgrsrxj8mjpjcq1n7mn2p1shpxif4zg9y5h09c7vy20s146";
    inherit dependencies buildDependencies features;
  };
  proc_macro2_0_3_6_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "proc-macro2";
    version = "0.3.6";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "1viqlvsknzvgc2j0bcz53n94zxv7c816py7hv2r27y0bv1dq4iqp";
    inherit dependencies buildDependencies features;
  };
  pulldown_cmark_0_1_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "pulldown-cmark";
    version = "0.1.2";
    authors = [ "Raph Levien <raph@google.com>" ];
    sha256 = "0imc6m2bxk4j8y5qfp9x9sjnbrz7cz4i7irv4dfqjp4cgblmg5l8";
    crateBin = [ {  name = "pulldown-cmark"; } ];
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  quine_mc_cluskey_0_2_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "quine-mc_cluskey";
    version = "0.2.4";
    authors = [ "Oliver Schneider <git-spam-no-reply9815368754983@oli-obk.de>" ];
    sha256 = "08l9w7ydvxqyd8m1jcv37pv55w1m1ppkjbrvi8wqmyv3rfv0bi3q";
    inherit dependencies buildDependencies features;
  };
  quote_0_5_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "quote";
    version = "0.5.1";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "0jppgddqp6vp67ns4hpyf644n5678fligp711isp0xkvfv19la3r";
    inherit dependencies buildDependencies features;
  };
  rand_0_4_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "rand";
    version = "0.4.2";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0h8pkg23wb67i8904sm76iyr1jlmhklb85vbpz9c9191a24xzkfm";
    inherit dependencies buildDependencies features;
  };
  redox_syscall_0_1_37_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "redox_syscall";
    version = "0.1.37";
    authors = [ "Jeremy Soller <jackpot51@gmail.com>" ];
    sha256 = "0qa0jl9cr3qp80an8vshp2mcn8rzvwiavs1398hq1vsjw7pc3h2v";
    libName = "syscall";
    inherit dependencies buildDependencies features;
  };
  regex_0_2_10_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "regex";
    version = "0.2.10";
    authors = [ "The Rust Project Developers" ];
    sha256 = "0cwdmcllssm984b5nnpr55rgla1yzw31kmp2imxdpgk6hvlhf1ca";
    inherit dependencies buildDependencies features;
  };
  regex_syntax_0_5_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "regex-syntax";
    version = "0.5.5";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1m5v66r6xxglgkdl1ci23qq0bl0k2wqplm6li4pmg1k7szvgxcbp";
    inherit dependencies buildDependencies features;
  };
  semver_0_9_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "semver";
    version = "0.9.0";
    authors = [ "Steve Klabnik <steve@steveklabnik.com>" "The Rust Project Developers" ];
    sha256 = "0azak2lb2wc36s3x15az886kck7rpnksrw14lalm157rg9sc9z63";
    inherit dependencies buildDependencies features;
  };
  semver_parser_0_7_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "semver-parser";
    version = "0.7.0";
    authors = [ "Steve Klabnik <steve@steveklabnik.com>" ];
    sha256 = "1da66c8413yakx0y15k8c055yna5lyb6fr0fw9318kdwkrk5k12h";
    inherit dependencies buildDependencies features;
  };
  serde_1_0_38_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "serde";
    version = "1.0.38";
    authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "0dri7vmzjsfmak1qq5wdinykqqvd5shpms504p8acpgyx7817jgk";
    inherit dependencies buildDependencies features;
  };
  serde_derive_1_0_38_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "serde_derive";
    version = "1.0.38";
    authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "027c13sbnqkfzc8vxx0m6wnkr68im8kdbkbnix07dgw1l616yw0m";
    procMacro = true;
    inherit dependencies buildDependencies features;
  };
  serde_derive_internals_0_23_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "serde_derive_internals";
    version = "0.23.1";
    authors = [ "Erick Tryzelaar <erick.tryzelaar@gmail.com>" "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "0bjgcn2irh6sd34q3j3xkbn5ghfgiv3cfdlffb31lh0bikwpk1b4";
    inherit dependencies buildDependencies features;
  };
  syn_0_13_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "syn";
    version = "0.13.1";
    authors = [ "David Tolnay <dtolnay@gmail.com>" ];
    sha256 = "1pimp7fpvillhz06xz0k6450h9nis3ab6h1j2hzrzykrpxs2qnyg";
    inherit dependencies buildDependencies features;
  };
  thread_local_0_3_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "thread_local";
    version = "0.3.5";
    authors = [ "Amanieu d'Antras <amanieu@gmail.com>" ];
    sha256 = "0mkp0sp91aqsk7brgygai4igv751r1754rsxn37mig3ag5rx8np6";
    inherit dependencies buildDependencies features;
  };
  time_0_1_39_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "time";
    version = "0.1.39";
    authors = [ "The Rust Project Developers" ];
    sha256 = "1ryy3bwhvyzj6fym123il38mk9ranm4vradj2a47l5ij8jd7w5if";
    inherit dependencies buildDependencies features;
  };
  toml_0_4_6_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "toml";
    version = "0.4.6";
    authors = [ "Alex Crichton <alex@alexcrichton.com>" ];
    sha256 = "0rfl7lyb5f67spk69s604nw87f97g7fvv36hj9v88qlr2bwyrn8v";
    inherit dependencies buildDependencies features;
  };
  ucd_util_0_1_1_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "ucd-util";
    version = "0.1.1";
    authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
    sha256 = "02a8h3siipx52b832xc8m8rwasj6nx9jpiwfldw8hp6k205hgkn0";
    inherit dependencies buildDependencies features;
  };
  unicode_bidi_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unicode-bidi";
    version = "0.3.4";
    authors = [ "The Servo Project Developers" ];
    sha256 = "0lcd6jasrf8p9p0q20qyf10c6xhvw40m2c4rr105hbk6zy26nj1q";
    libName = "unicode_bidi";
    inherit dependencies buildDependencies features;
  };
  unicode_normalization_0_1_5_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unicode-normalization";
    version = "0.1.5";
    authors = [ "kwantam <kwantam@gmail.com>" ];
    sha256 = "0hg29g86fca7b65mwk4sm5s838js6bqrl0gabadbazvbsgjam0j5";
    inherit dependencies buildDependencies features;
  };
  unicode_xid_0_1_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unicode-xid";
    version = "0.1.0";
    authors = [ "erick.tryzelaar <erick.tryzelaar@gmail.com>" "kwantam <kwantam@gmail.com>" ];
    sha256 = "05wdmwlfzxhq3nhsxn6wx4q8dhxzzfb9szsz6wiw092m1rjj01zj";
    inherit dependencies buildDependencies features;
  };
  unreachable_1_0_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "unreachable";
    version = "1.0.0";
    authors = [ "Jonathan Reem <jonathan.reem@gmail.com>" ];
    sha256 = "1am8czbk5wwr25gbp2zr007744fxjshhdqjz9liz7wl4pnv3whcf";
    inherit dependencies buildDependencies features;
  };
  url_1_7_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "url";
    version = "1.7.0";
    authors = [ "The rust-url developers" ];
    sha256 = "0333ynhkp47hna88aamz1zpk4lxyzx4ab9n7yhc75g14w27cv8jj";
    inherit dependencies buildDependencies features;
  };
  utf8_ranges_1_0_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "utf8-ranges";
    version = "1.0.0";
    authors = [ "Andrew Gallant <jamslam@gmail.com>" ];
    sha256 = "0rzmqprwjv9yp1n0qqgahgm24872x6c0xddfym5pfndy7a36vkn0";
    inherit dependencies buildDependencies features;
  };
  uuid_0_6_3_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "uuid";
    version = "0.6.3";
    authors = [ "Ashley Mannix<ashleymannix@live.com.au>" "Christopher Armstrong" "Dylan DPC<dylan.dpc@gmail.com>" "Hunar Roop Kahlon<hunar.roop@gmail.com>" ];
    sha256 = "1kjp5xglhab4saaikn95zn3mr4zja7484pv307cb5bxm2sawb8p6";
    inherit dependencies buildDependencies features;
  };
  void_1_0_2_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "void";
    version = "1.0.2";
    authors = [ "Jonathan Reem <jonathan.reem@gmail.com>" ];
    sha256 = "0h1dm0dx8dhf56a83k68mijyxigqhizpskwxfdrs1drwv2cdclv3";
    inherit dependencies buildDependencies features;
  };
  winapi_0_3_4_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi";
    version = "0.3.4";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "1qbrf5dcnd8j36cawby5d9r5vx07r0l4ryf672pfncnp8895k9lx";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  winapi_i686_pc_windows_gnu_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi-i686-pc-windows-gnu";
    version = "0.4.0";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "05ihkij18r4gamjpxj4gra24514can762imjzlmak5wlzidplzrp";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  winapi_x86_64_pc_windows_gnu_0_4_0_ = { dependencies?[], buildDependencies?[], features?[] }: buildRustCrate {
    crateName = "winapi-x86_64-pc-windows-gnu";
    version = "0.4.0";
    authors = [ "Peter Atashian <retep998@gmail.com>" ];
    sha256 = "0n1ylmlsb8yg1v583i4xy0qmqg42275flvbc51hdqjjfjcl9vlbj";
    build = "build.rs";
    inherit dependencies buildDependencies features;
  };
  aho_corasick_0_6_4 = { features?(aho_corasick_0_6_4_features {}) }: aho_corasick_0_6_4_ {
    dependencies = mapFeatures features ([ memchr_2_0_1 ]);
  };
  aho_corasick_0_6_4_features = f: updateFeatures f (rec {
    aho_corasick_0_6_4.default = (f.aho_corasick_0_6_4.default or true);
    memchr_2_0_1.default = true;
  }) [ memchr_2_0_1_features ];
  bitflags_0_9_1 = { features?(bitflags_0_9_1_features {}) }: bitflags_0_9_1_ {
    features = mkFeatures (features.bitflags_0_9_1 or {});
  };
  bitflags_0_9_1_features = f: updateFeatures f (rec {
    bitflags_0_9_1.default = (f.bitflags_0_9_1.default or true);
    bitflags_0_9_1.example_generated =
      (f.bitflags_0_9_1.example_generated or false) ||
      (f.bitflags_0_9_1.default or false) ||
      (bitflags_0_9_1.default or false);
  }) [];
  bitflags_1_0_1 = { features?(bitflags_1_0_1_features {}) }: bitflags_1_0_1_ {
    features = mkFeatures (features.bitflags_1_0_1 or {});
  };
  bitflags_1_0_1_features = f: updateFeatures f (rec {
    bitflags_1_0_1.default = (f.bitflags_1_0_1.default or true);
    bitflags_1_0_1.example_generated =
      (f.bitflags_1_0_1.example_generated or false) ||
      (f.bitflags_1_0_1.default or false) ||
      (bitflags_1_0_1.default or false);
  }) [];
  cfg_if_0_1_2 = { features?(cfg_if_0_1_2_features {}) }: cfg_if_0_1_2_ {};
  cfg_if_0_1_2_features = f: updateFeatures f (rec {
    cfg_if_0_1_2.default = (f.cfg_if_0_1_2.default or true);
  }) [];
  chrono_0_4_2 = { features?(chrono_0_4_2_features {}) }: chrono_0_4_2_ {
    dependencies = mapFeatures features ([ num_integer_0_1_36 num_traits_0_2_2 ]
      ++ (if features.chrono_0_4_2.time or false then [ time_0_1_39 ] else []));
    features = mkFeatures (features.chrono_0_4_2 or {});
  };
  chrono_0_4_2_features = f: updateFeatures f (rec {
    chrono_0_4_2.clock =
      (f.chrono_0_4_2.clock or false) ||
      (f.chrono_0_4_2.default or false) ||
      (chrono_0_4_2.default or false);
    chrono_0_4_2.default = (f.chrono_0_4_2.default or true);
    chrono_0_4_2.time =
      (f.chrono_0_4_2.time or false) ||
      (f.chrono_0_4_2.clock or false) ||
      (chrono_0_4_2.clock or false);
    num_integer_0_1_36.default = (f.num_integer_0_1_36.default or false);
    num_traits_0_2_2.default = (f.num_traits_0_2_2.default or false);
    time_0_1_39.default = true;
  }) [ num_integer_0_1_36_features num_traits_0_2_2_features time_0_1_39_features ];
  clippy_0_0_194 = { features?(clippy_0_0_194_features {}) }: clippy_0_0_194_ {
    dependencies = mapFeatures features ([ clippy_lints_0_0_194 regex_0_2_10 semver_0_9_0 ]);
    features = mkFeatures (features.clippy_0_0_194 or {});
  };
  clippy_0_0_194_features = f: updateFeatures f (rec {
    clippy_0_0_194.default = (f.clippy_0_0_194.default or true);
    clippy_lints_0_0_194.default = true;
    regex_0_2_10.default = true;
    semver_0_9_0.default = true;
  }) [ clippy_lints_0_0_194_features regex_0_2_10_features semver_0_9_0_features ];
  clippy_lints_0_0_194 = { features?(clippy_lints_0_0_194_features {}) }: clippy_lints_0_0_194_ {
    dependencies = mapFeatures features ([ if_chain_0_1_2 itertools_0_7_8 lazy_static_1_0_0 matches_0_1_6 pulldown_cmark_0_1_2 quine_mc_cluskey_0_2_4 regex_syntax_0_5_5 semver_0_9_0 serde_1_0_38 serde_derive_1_0_38 toml_0_4_6 unicode_normalization_0_1_5 url_1_7_0 ]);
    features = mkFeatures (features.clippy_lints_0_0_194 or {});
  };
  clippy_lints_0_0_194_features = f: updateFeatures f (rec {
    clippy_lints_0_0_194.default = (f.clippy_lints_0_0_194.default or true);
    if_chain_0_1_2.default = true;
    itertools_0_7_8.default = true;
    lazy_static_1_0_0.default = true;
    matches_0_1_6.default = true;
    pulldown_cmark_0_1_2.default = true;
    quine_mc_cluskey_0_2_4.default = true;
    regex_syntax_0_5_5.default = true;
    semver_0_9_0.default = true;
    serde_1_0_38.default = true;
    serde_derive_1_0_38.default = true;
    toml_0_4_6.default = true;
    unicode_normalization_0_1_5.default = true;
    url_1_7_0.default = true;
  }) [ if_chain_0_1_2_features itertools_0_7_8_features lazy_static_1_0_0_features matches_0_1_6_features pulldown_cmark_0_1_2_features quine_mc_cluskey_0_2_4_features regex_syntax_0_5_5_features semver_0_9_0_features serde_1_0_38_features serde_derive_1_0_38_features toml_0_4_6_features unicode_normalization_0_1_5_features url_1_7_0_features ];
  dbus_0_6_1 = { features?(dbus_0_6_1_features {}) }: dbus_0_6_1_ {
    dependencies = mapFeatures features ([ libc_0_2_40 libdbus_sys_0_1_3 ]);
    features = mkFeatures (features.dbus_0_6_1 or {});
  };
  dbus_0_6_1_features = f: updateFeatures f (rec {
    dbus_0_6_1.default = (f.dbus_0_6_1.default or true);
    libc_0_2_40.default = true;
    libdbus_sys_0_1_3.default = true;
  }) [ libc_0_2_40_features libdbus_sys_0_1_3_features ];
  dwm_status_0_3_1 = { features?(dwm_status_0_3_1_features {}) }: dwm_status_0_3_1_ {
    dependencies = mapFeatures features ([ chrono_0_4_2 dbus_0_6_1 inotify_0_5_1 libnotify_1_0_3 uuid_0_6_3 ]
      ++ (if features.dwm_status_0_3_1.clippy or false then [ clippy_0_0_194 ] else []));
    features = mkFeatures (features.dwm_status_0_3_1 or {});
  };
  dwm_status_0_3_1_features = f: updateFeatures f (rec {
    chrono_0_4_2.default = true;
    clippy_0_0_194.default = true;
    dbus_0_6_1.default = true;
    dwm_status_0_3_1.clippy =
      (f.dwm_status_0_3_1.clippy or false) ||
      (f.dwm_status_0_3_1.dev or false) ||
      (dwm_status_0_3_1.dev or false);
    dwm_status_0_3_1.default = (f.dwm_status_0_3_1.default or true);
    inotify_0_5_1.default = true;
    libnotify_1_0_3.default = true;
    uuid_0_6_3.default = true;
    uuid_0_6_3.v4 = true;
  }) [ chrono_0_4_2_features clippy_0_0_194_features dbus_0_6_1_features inotify_0_5_1_features libnotify_1_0_3_features uuid_0_6_3_features ];
  either_1_5_0 = { features?(either_1_5_0_features {}) }: either_1_5_0_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.either_1_5_0 or {});
  };
  either_1_5_0_features = f: updateFeatures f (rec {
    either_1_5_0.default = (f.either_1_5_0.default or true);
    either_1_5_0.use_std =
      (f.either_1_5_0.use_std or false) ||
      (f.either_1_5_0.default or false) ||
      (either_1_5_0.default or false);
  }) [];
  fuchsia_zircon_0_3_3 = { features?(fuchsia_zircon_0_3_3_features {}) }: fuchsia_zircon_0_3_3_ {
    dependencies = mapFeatures features ([ bitflags_1_0_1 fuchsia_zircon_sys_0_3_3 ]);
  };
  fuchsia_zircon_0_3_3_features = f: updateFeatures f (rec {
    bitflags_1_0_1.default = true;
    fuchsia_zircon_0_3_3.default = (f.fuchsia_zircon_0_3_3.default or true);
    fuchsia_zircon_sys_0_3_3.default = true;
  }) [ bitflags_1_0_1_features fuchsia_zircon_sys_0_3_3_features ];
  fuchsia_zircon_sys_0_3_3 = { features?(fuchsia_zircon_sys_0_3_3_features {}) }: fuchsia_zircon_sys_0_3_3_ {};
  fuchsia_zircon_sys_0_3_3_features = f: updateFeatures f (rec {
    fuchsia_zircon_sys_0_3_3.default = (f.fuchsia_zircon_sys_0_3_3.default or true);
  }) [];
  futures_0_1_21 = { features?(futures_0_1_21_features {}) }: futures_0_1_21_ {
    features = mkFeatures (features.futures_0_1_21 or {});
  };
  futures_0_1_21_features = f: updateFeatures f (rec {
    futures_0_1_21.default = (f.futures_0_1_21.default or true);
    futures_0_1_21.use_std =
      (f.futures_0_1_21.use_std or false) ||
      (f.futures_0_1_21.default or false) ||
      (futures_0_1_21.default or false);
    futures_0_1_21.with-deprecated =
      (f.futures_0_1_21.with-deprecated or false) ||
      (f.futures_0_1_21.default or false) ||
      (futures_0_1_21.default or false);
  }) [];
  gdk_pixbuf_0_3_0 = { features?(gdk_pixbuf_0_3_0_features {}) }: gdk_pixbuf_0_3_0_ {
    dependencies = mapFeatures features ([ gdk_pixbuf_sys_0_5_0 glib_0_4_1 glib_sys_0_5_0 gobject_sys_0_5_0 libc_0_2_40 ]);
    buildDependencies = mapFeatures features ([]);
    features = mkFeatures (features.gdk_pixbuf_0_3_0 or {});
  };
  gdk_pixbuf_0_3_0_features = f: updateFeatures f (rec {
    gdk_pixbuf_0_3_0.default = (f.gdk_pixbuf_0_3_0.default or true);
    gdk_pixbuf_0_3_0.gtk-rs-lgpl-docs =
      (f.gdk_pixbuf_0_3_0.gtk-rs-lgpl-docs or false) ||
      (f.gdk_pixbuf_0_3_0.embed-lgpl-docs or false) ||
      (gdk_pixbuf_0_3_0.embed-lgpl-docs or false) ||
      (f.gdk_pixbuf_0_3_0.purge-lgpl-docs or false) ||
      (gdk_pixbuf_0_3_0.purge-lgpl-docs or false);
    gdk_pixbuf_0_3_0.v2_28 =
      (f.gdk_pixbuf_0_3_0.v2_28 or false) ||
      (f.gdk_pixbuf_0_3_0.v2_30 or false) ||
      (gdk_pixbuf_0_3_0.v2_30 or false);
    gdk_pixbuf_0_3_0.v2_30 =
      (f.gdk_pixbuf_0_3_0.v2_30 or false) ||
      (f.gdk_pixbuf_0_3_0.v2_32 or false) ||
      (gdk_pixbuf_0_3_0.v2_32 or false);
    gdk_pixbuf_0_3_0.v2_32 =
      (f.gdk_pixbuf_0_3_0.v2_32 or false) ||
      (f.gdk_pixbuf_0_3_0.v2_36 or false) ||
      (gdk_pixbuf_0_3_0.v2_36 or false);
    gdk_pixbuf_sys_0_5_0.default = true;
    gdk_pixbuf_sys_0_5_0.dox =
      (f.gdk_pixbuf_sys_0_5_0.dox or false) ||
      (gdk_pixbuf_0_3_0.dox or false) ||
      (f.gdk_pixbuf_0_3_0.dox or false);
    gdk_pixbuf_sys_0_5_0.v2_28 =
      (f.gdk_pixbuf_sys_0_5_0.v2_28 or false) ||
      (gdk_pixbuf_0_3_0.v2_28 or false) ||
      (f.gdk_pixbuf_0_3_0.v2_28 or false);
    gdk_pixbuf_sys_0_5_0.v2_30 =
      (f.gdk_pixbuf_sys_0_5_0.v2_30 or false) ||
      (gdk_pixbuf_0_3_0.v2_30 or false) ||
      (f.gdk_pixbuf_0_3_0.v2_30 or false);
    gdk_pixbuf_sys_0_5_0.v2_32 =
      (f.gdk_pixbuf_sys_0_5_0.v2_32 or false) ||
      (gdk_pixbuf_0_3_0.v2_32 or false) ||
      (f.gdk_pixbuf_0_3_0.v2_32 or false);
    gdk_pixbuf_sys_0_5_0.v2_36 =
      (f.gdk_pixbuf_sys_0_5_0.v2_36 or false) ||
      (gdk_pixbuf_0_3_0.v2_36 or false) ||
      (f.gdk_pixbuf_0_3_0.v2_36 or false);
    glib_0_4_1.default = true;
    glib_0_4_1.dox =
      (f.glib_0_4_1.dox or false) ||
      (gdk_pixbuf_0_3_0.dox or false) ||
      (f.gdk_pixbuf_0_3_0.dox or false);
    glib_sys_0_5_0.default = true;
    gobject_sys_0_5_0.default = true;
    libc_0_2_40.default = true;
  }) [ gdk_pixbuf_sys_0_5_0_features glib_0_4_1_features glib_sys_0_5_0_features gobject_sys_0_5_0_features libc_0_2_40_features ];
  gdk_pixbuf_sys_0_5_0 = { features?(gdk_pixbuf_sys_0_5_0_features {}) }: gdk_pixbuf_sys_0_5_0_ {
    dependencies = mapFeatures features ([ bitflags_1_0_1 gio_sys_0_5_0 glib_sys_0_5_0 gobject_sys_0_5_0 libc_0_2_40 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_9 ]);
    features = mkFeatures (features.gdk_pixbuf_sys_0_5_0 or {});
  };
  gdk_pixbuf_sys_0_5_0_features = f: updateFeatures f (rec {
    bitflags_1_0_1.default = true;
    gdk_pixbuf_sys_0_5_0.default = (f.gdk_pixbuf_sys_0_5_0.default or true);
    gdk_pixbuf_sys_0_5_0.v2_28 =
      (f.gdk_pixbuf_sys_0_5_0.v2_28 or false) ||
      (f.gdk_pixbuf_sys_0_5_0.v2_30 or false) ||
      (gdk_pixbuf_sys_0_5_0.v2_30 or false);
    gdk_pixbuf_sys_0_5_0.v2_30 =
      (f.gdk_pixbuf_sys_0_5_0.v2_30 or false) ||
      (f.gdk_pixbuf_sys_0_5_0.v2_32 or false) ||
      (gdk_pixbuf_sys_0_5_0.v2_32 or false);
    gdk_pixbuf_sys_0_5_0.v2_32 =
      (f.gdk_pixbuf_sys_0_5_0.v2_32 or false) ||
      (f.gdk_pixbuf_sys_0_5_0.v2_36 or false) ||
      (gdk_pixbuf_sys_0_5_0.v2_36 or false);
    gio_sys_0_5_0.default = true;
    glib_sys_0_5_0.default = true;
    gobject_sys_0_5_0.default = true;
    libc_0_2_40.default = true;
    pkg_config_0_3_9.default = true;
  }) [ bitflags_1_0_1_features gio_sys_0_5_0_features glib_sys_0_5_0_features gobject_sys_0_5_0_features libc_0_2_40_features pkg_config_0_3_9_features ];
  getopts_0_2_17 = { features?(getopts_0_2_17_features {}) }: getopts_0_2_17_ {};
  getopts_0_2_17_features = f: updateFeatures f (rec {
    getopts_0_2_17.default = (f.getopts_0_2_17.default or true);
  }) [];
  gio_sys_0_5_0 = { features?(gio_sys_0_5_0_features {}) }: gio_sys_0_5_0_ {
    dependencies = mapFeatures features ([ bitflags_1_0_1 glib_sys_0_5_0 gobject_sys_0_5_0 libc_0_2_40 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_9 ]);
    features = mkFeatures (features.gio_sys_0_5_0 or {});
  };
  gio_sys_0_5_0_features = f: updateFeatures f (rec {
    bitflags_1_0_1.default = true;
    gio_sys_0_5_0.default = (f.gio_sys_0_5_0.default or true);
    gio_sys_0_5_0.v2_34 =
      (f.gio_sys_0_5_0.v2_34 or false) ||
      (f.gio_sys_0_5_0.v2_36 or false) ||
      (gio_sys_0_5_0.v2_36 or false);
    gio_sys_0_5_0.v2_36 =
      (f.gio_sys_0_5_0.v2_36 or false) ||
      (f.gio_sys_0_5_0.v2_38 or false) ||
      (gio_sys_0_5_0.v2_38 or false);
    gio_sys_0_5_0.v2_38 =
      (f.gio_sys_0_5_0.v2_38 or false) ||
      (f.gio_sys_0_5_0.v2_40 or false) ||
      (gio_sys_0_5_0.v2_40 or false);
    gio_sys_0_5_0.v2_40 =
      (f.gio_sys_0_5_0.v2_40 or false) ||
      (f.gio_sys_0_5_0.v2_42 or false) ||
      (gio_sys_0_5_0.v2_42 or false);
    gio_sys_0_5_0.v2_42 =
      (f.gio_sys_0_5_0.v2_42 or false) ||
      (f.gio_sys_0_5_0.v2_44 or false) ||
      (gio_sys_0_5_0.v2_44 or false);
    gio_sys_0_5_0.v2_44 =
      (f.gio_sys_0_5_0.v2_44 or false) ||
      (f.gio_sys_0_5_0.v2_46 or false) ||
      (gio_sys_0_5_0.v2_46 or false);
    gio_sys_0_5_0.v2_46 =
      (f.gio_sys_0_5_0.v2_46 or false) ||
      (f.gio_sys_0_5_0.v2_48 or false) ||
      (gio_sys_0_5_0.v2_48 or false);
    gio_sys_0_5_0.v2_48 =
      (f.gio_sys_0_5_0.v2_48 or false) ||
      (f.gio_sys_0_5_0.v2_50 or false) ||
      (gio_sys_0_5_0.v2_50 or false);
    gio_sys_0_5_0.v2_50 =
      (f.gio_sys_0_5_0.v2_50 or false) ||
      (f.gio_sys_0_5_0.v2_52 or false) ||
      (gio_sys_0_5_0.v2_52 or false);
    gio_sys_0_5_0.v2_52 =
      (f.gio_sys_0_5_0.v2_52 or false) ||
      (f.gio_sys_0_5_0.v2_54 or false) ||
      (gio_sys_0_5_0.v2_54 or false);
    glib_sys_0_5_0.default = true;
    gobject_sys_0_5_0.default = true;
    libc_0_2_40.default = true;
    pkg_config_0_3_9.default = true;
  }) [ bitflags_1_0_1_features glib_sys_0_5_0_features gobject_sys_0_5_0_features libc_0_2_40_features pkg_config_0_3_9_features ];
  glib_0_4_1 = { features?(glib_0_4_1_features {}) }: glib_0_4_1_ {
    dependencies = mapFeatures features ([ bitflags_1_0_1 glib_sys_0_5_0 gobject_sys_0_5_0 lazy_static_1_0_0 libc_0_2_40 ]);
    features = mkFeatures (features.glib_0_4_1 or {});
  };
  glib_0_4_1_features = f: updateFeatures f (rec {
    bitflags_1_0_1.default = true;
    glib_0_4_1.default = (f.glib_0_4_1.default or true);
    glib_0_4_1.v2_34 =
      (f.glib_0_4_1.v2_34 or false) ||
      (f.glib_0_4_1.v2_38 or false) ||
      (glib_0_4_1.v2_38 or false);
    glib_0_4_1.v2_38 =
      (f.glib_0_4_1.v2_38 or false) ||
      (f.glib_0_4_1.v2_40 or false) ||
      (glib_0_4_1.v2_40 or false);
    glib_0_4_1.v2_40 =
      (f.glib_0_4_1.v2_40 or false) ||
      (f.glib_0_4_1.v2_44 or false) ||
      (glib_0_4_1.v2_44 or false);
    glib_0_4_1.v2_44 =
      (f.glib_0_4_1.v2_44 or false) ||
      (f.glib_0_4_1.v2_46 or false) ||
      (glib_0_4_1.v2_46 or false);
    glib_0_4_1.v2_46 =
      (f.glib_0_4_1.v2_46 or false) ||
      (f.glib_0_4_1.v2_48 or false) ||
      (glib_0_4_1.v2_48 or false);
    glib_0_4_1.v2_48 =
      (f.glib_0_4_1.v2_48 or false) ||
      (f.glib_0_4_1.v2_50 or false) ||
      (glib_0_4_1.v2_50 or false);
    glib_0_4_1.v2_50 =
      (f.glib_0_4_1.v2_50 or false) ||
      (f.glib_0_4_1.v2_52 or false) ||
      (glib_0_4_1.v2_52 or false);
    glib_0_4_1.v2_52 =
      (f.glib_0_4_1.v2_52 or false) ||
      (f.glib_0_4_1.v2_54 or false) ||
      (glib_0_4_1.v2_54 or false);
    glib_sys_0_5_0.default = true;
    glib_sys_0_5_0.dox =
      (f.glib_sys_0_5_0.dox or false) ||
      (glib_0_4_1.dox or false) ||
      (f.glib_0_4_1.dox or false);
    glib_sys_0_5_0.v2_34 =
      (f.glib_sys_0_5_0.v2_34 or false) ||
      (glib_0_4_1.v2_34 or false) ||
      (f.glib_0_4_1.v2_34 or false);
    glib_sys_0_5_0.v2_38 =
      (f.glib_sys_0_5_0.v2_38 or false) ||
      (glib_0_4_1.v2_38 or false) ||
      (f.glib_0_4_1.v2_38 or false);
    glib_sys_0_5_0.v2_40 =
      (f.glib_sys_0_5_0.v2_40 or false) ||
      (glib_0_4_1.v2_40 or false) ||
      (f.glib_0_4_1.v2_40 or false);
    glib_sys_0_5_0.v2_44 =
      (f.glib_sys_0_5_0.v2_44 or false) ||
      (glib_0_4_1.v2_44 or false) ||
      (f.glib_0_4_1.v2_44 or false);
    glib_sys_0_5_0.v2_46 =
      (f.glib_sys_0_5_0.v2_46 or false) ||
      (glib_0_4_1.v2_46 or false) ||
      (f.glib_0_4_1.v2_46 or false);
    glib_sys_0_5_0.v2_48 =
      (f.glib_sys_0_5_0.v2_48 or false) ||
      (glib_0_4_1.v2_48 or false) ||
      (f.glib_0_4_1.v2_48 or false);
    glib_sys_0_5_0.v2_50 =
      (f.glib_sys_0_5_0.v2_50 or false) ||
      (glib_0_4_1.v2_50 or false) ||
      (f.glib_0_4_1.v2_50 or false);
    glib_sys_0_5_0.v2_52 =
      (f.glib_sys_0_5_0.v2_52 or false) ||
      (glib_0_4_1.v2_52 or false) ||
      (f.glib_0_4_1.v2_52 or false);
    glib_sys_0_5_0.v2_54 =
      (f.glib_sys_0_5_0.v2_54 or false) ||
      (glib_0_4_1.v2_54 or false) ||
      (f.glib_0_4_1.v2_54 or false);
    gobject_sys_0_5_0.default = true;
    gobject_sys_0_5_0.dox =
      (f.gobject_sys_0_5_0.dox or false) ||
      (glib_0_4_1.dox or false) ||
      (f.glib_0_4_1.dox or false);
    gobject_sys_0_5_0.v2_34 =
      (f.gobject_sys_0_5_0.v2_34 or false) ||
      (glib_0_4_1.v2_34 or false) ||
      (f.glib_0_4_1.v2_34 or false);
    gobject_sys_0_5_0.v2_38 =
      (f.gobject_sys_0_5_0.v2_38 or false) ||
      (glib_0_4_1.v2_38 or false) ||
      (f.glib_0_4_1.v2_38 or false);
    gobject_sys_0_5_0.v2_44 =
      (f.gobject_sys_0_5_0.v2_44 or false) ||
      (glib_0_4_1.v2_44 or false) ||
      (f.glib_0_4_1.v2_44 or false);
    gobject_sys_0_5_0.v2_46 =
      (f.gobject_sys_0_5_0.v2_46 or false) ||
      (glib_0_4_1.v2_46 or false) ||
      (f.glib_0_4_1.v2_46 or false);
    gobject_sys_0_5_0.v2_54 =
      (f.gobject_sys_0_5_0.v2_54 or false) ||
      (glib_0_4_1.v2_54 or false) ||
      (f.glib_0_4_1.v2_54 or false);
    lazy_static_1_0_0.default = true;
    libc_0_2_40.default = true;
  }) [ bitflags_1_0_1_features glib_sys_0_5_0_features gobject_sys_0_5_0_features lazy_static_1_0_0_features libc_0_2_40_features ];
  glib_sys_0_5_0 = { features?(glib_sys_0_5_0_features {}) }: glib_sys_0_5_0_ {
    dependencies = mapFeatures features ([ bitflags_1_0_1 libc_0_2_40 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_9 ]);
    features = mkFeatures (features.glib_sys_0_5_0 or {});
  };
  glib_sys_0_5_0_features = f: updateFeatures f (rec {
    bitflags_1_0_1.default = true;
    glib_sys_0_5_0.default = (f.glib_sys_0_5_0.default or true);
    glib_sys_0_5_0.v2_34 =
      (f.glib_sys_0_5_0.v2_34 or false) ||
      (f.glib_sys_0_5_0.v2_36 or false) ||
      (glib_sys_0_5_0.v2_36 or false);
    glib_sys_0_5_0.v2_36 =
      (f.glib_sys_0_5_0.v2_36 or false) ||
      (f.glib_sys_0_5_0.v2_38 or false) ||
      (glib_sys_0_5_0.v2_38 or false);
    glib_sys_0_5_0.v2_38 =
      (f.glib_sys_0_5_0.v2_38 or false) ||
      (f.glib_sys_0_5_0.v2_40 or false) ||
      (glib_sys_0_5_0.v2_40 or false);
    glib_sys_0_5_0.v2_40 =
      (f.glib_sys_0_5_0.v2_40 or false) ||
      (f.glib_sys_0_5_0.v2_44 or false) ||
      (glib_sys_0_5_0.v2_44 or false);
    glib_sys_0_5_0.v2_44 =
      (f.glib_sys_0_5_0.v2_44 or false) ||
      (f.glib_sys_0_5_0.v2_46 or false) ||
      (glib_sys_0_5_0.v2_46 or false);
    glib_sys_0_5_0.v2_46 =
      (f.glib_sys_0_5_0.v2_46 or false) ||
      (f.glib_sys_0_5_0.v2_48 or false) ||
      (glib_sys_0_5_0.v2_48 or false);
    glib_sys_0_5_0.v2_48 =
      (f.glib_sys_0_5_0.v2_48 or false) ||
      (f.glib_sys_0_5_0.v2_50 or false) ||
      (glib_sys_0_5_0.v2_50 or false);
    glib_sys_0_5_0.v2_50 =
      (f.glib_sys_0_5_0.v2_50 or false) ||
      (f.glib_sys_0_5_0.v2_52 or false) ||
      (glib_sys_0_5_0.v2_52 or false);
    glib_sys_0_5_0.v2_52 =
      (f.glib_sys_0_5_0.v2_52 or false) ||
      (f.glib_sys_0_5_0.v2_54 or false) ||
      (glib_sys_0_5_0.v2_54 or false);
    libc_0_2_40.default = true;
    pkg_config_0_3_9.default = true;
  }) [ bitflags_1_0_1_features libc_0_2_40_features pkg_config_0_3_9_features ];
  gobject_sys_0_5_0 = { features?(gobject_sys_0_5_0_features {}) }: gobject_sys_0_5_0_ {
    dependencies = mapFeatures features ([ bitflags_1_0_1 glib_sys_0_5_0 libc_0_2_40 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_9 ]);
    features = mkFeatures (features.gobject_sys_0_5_0 or {});
  };
  gobject_sys_0_5_0_features = f: updateFeatures f (rec {
    bitflags_1_0_1.default = true;
    glib_sys_0_5_0.default = true;
    gobject_sys_0_5_0.default = (f.gobject_sys_0_5_0.default or true);
    gobject_sys_0_5_0.v2_34 =
      (f.gobject_sys_0_5_0.v2_34 or false) ||
      (f.gobject_sys_0_5_0.v2_36 or false) ||
      (gobject_sys_0_5_0.v2_36 or false);
    gobject_sys_0_5_0.v2_36 =
      (f.gobject_sys_0_5_0.v2_36 or false) ||
      (f.gobject_sys_0_5_0.v2_38 or false) ||
      (gobject_sys_0_5_0.v2_38 or false);
    gobject_sys_0_5_0.v2_38 =
      (f.gobject_sys_0_5_0.v2_38 or false) ||
      (f.gobject_sys_0_5_0.v2_42 or false) ||
      (gobject_sys_0_5_0.v2_42 or false);
    gobject_sys_0_5_0.v2_42 =
      (f.gobject_sys_0_5_0.v2_42 or false) ||
      (f.gobject_sys_0_5_0.v2_44 or false) ||
      (gobject_sys_0_5_0.v2_44 or false);
    gobject_sys_0_5_0.v2_44 =
      (f.gobject_sys_0_5_0.v2_44 or false) ||
      (f.gobject_sys_0_5_0.v2_46 or false) ||
      (gobject_sys_0_5_0.v2_46 or false);
    gobject_sys_0_5_0.v2_46 =
      (f.gobject_sys_0_5_0.v2_46 or false) ||
      (f.gobject_sys_0_5_0.v2_54 or false) ||
      (gobject_sys_0_5_0.v2_54 or false);
    libc_0_2_40.default = true;
    pkg_config_0_3_9.default = true;
  }) [ bitflags_1_0_1_features glib_sys_0_5_0_features libc_0_2_40_features pkg_config_0_3_9_features ];
  idna_0_1_4 = { features?(idna_0_1_4_features {}) }: idna_0_1_4_ {
    dependencies = mapFeatures features ([ matches_0_1_6 unicode_bidi_0_3_4 unicode_normalization_0_1_5 ]);
  };
  idna_0_1_4_features = f: updateFeatures f (rec {
    idna_0_1_4.default = (f.idna_0_1_4.default or true);
    matches_0_1_6.default = true;
    unicode_bidi_0_3_4.default = true;
    unicode_normalization_0_1_5.default = true;
  }) [ matches_0_1_6_features unicode_bidi_0_3_4_features unicode_normalization_0_1_5_features ];
  if_chain_0_1_2 = { features?(if_chain_0_1_2_features {}) }: if_chain_0_1_2_ {};
  if_chain_0_1_2_features = f: updateFeatures f (rec {
    if_chain_0_1_2.default = (f.if_chain_0_1_2.default or true);
  }) [];
  inotify_0_5_1 = { features?(inotify_0_5_1_features {}) }: inotify_0_5_1_ {
    dependencies = mapFeatures features ([ bitflags_1_0_1 futures_0_1_21 inotify_sys_0_1_2 libc_0_2_40 ]);
  };
  inotify_0_5_1_features = f: updateFeatures f (rec {
    bitflags_1_0_1.default = true;
    futures_0_1_21.default = true;
    inotify_0_5_1.default = (f.inotify_0_5_1.default or true);
    inotify_sys_0_1_2.default = true;
    libc_0_2_40.default = true;
  }) [ bitflags_1_0_1_features futures_0_1_21_features inotify_sys_0_1_2_features libc_0_2_40_features ];
  inotify_sys_0_1_2 = { features?(inotify_sys_0_1_2_features {}) }: inotify_sys_0_1_2_ {
    dependencies = mapFeatures features ([ libc_0_2_40 ]);
  };
  inotify_sys_0_1_2_features = f: updateFeatures f (rec {
    inotify_sys_0_1_2.default = (f.inotify_sys_0_1_2.default or true);
    libc_0_2_40.default = true;
  }) [ libc_0_2_40_features ];
  itertools_0_7_8 = { features?(itertools_0_7_8_features {}) }: itertools_0_7_8_ {
    dependencies = mapFeatures features ([ either_1_5_0 ]);
    features = mkFeatures (features.itertools_0_7_8 or {});
  };
  itertools_0_7_8_features = f: updateFeatures f (rec {
    either_1_5_0.default = (f.either_1_5_0.default or false);
    itertools_0_7_8.default = (f.itertools_0_7_8.default or true);
    itertools_0_7_8.use_std =
      (f.itertools_0_7_8.use_std or false) ||
      (f.itertools_0_7_8.default or false) ||
      (itertools_0_7_8.default or false);
  }) [ either_1_5_0_features ];
  lazy_static_1_0_0 = { features?(lazy_static_1_0_0_features {}) }: lazy_static_1_0_0_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.lazy_static_1_0_0 or {});
  };
  lazy_static_1_0_0_features = f: updateFeatures f (rec {
    lazy_static_1_0_0.compiletest_rs =
      (f.lazy_static_1_0_0.compiletest_rs or false) ||
      (f.lazy_static_1_0_0.compiletest or false) ||
      (lazy_static_1_0_0.compiletest or false);
    lazy_static_1_0_0.default = (f.lazy_static_1_0_0.default or true);
    lazy_static_1_0_0.nightly =
      (f.lazy_static_1_0_0.nightly or false) ||
      (f.lazy_static_1_0_0.spin_no_std or false) ||
      (lazy_static_1_0_0.spin_no_std or false);
    lazy_static_1_0_0.spin =
      (f.lazy_static_1_0_0.spin or false) ||
      (f.lazy_static_1_0_0.spin_no_std or false) ||
      (lazy_static_1_0_0.spin_no_std or false);
  }) [];
  libc_0_2_40 = { features?(libc_0_2_40_features {}) }: libc_0_2_40_ {
    features = mkFeatures (features.libc_0_2_40 or {});
  };
  libc_0_2_40_features = f: updateFeatures f (rec {
    libc_0_2_40.default = (f.libc_0_2_40.default or true);
    libc_0_2_40.use_std =
      (f.libc_0_2_40.use_std or false) ||
      (f.libc_0_2_40.default or false) ||
      (libc_0_2_40.default or false);
  }) [];
  libdbus_sys_0_1_3 = { features?(libdbus_sys_0_1_3_features {}) }: libdbus_sys_0_1_3_ {
    buildDependencies = mapFeatures features ([ pkg_config_0_3_9 ]);};
  libdbus_sys_0_1_3_features = f: updateFeatures f (rec {
    libdbus_sys_0_1_3.default = (f.libdbus_sys_0_1_3.default or true);
    pkg_config_0_3_9.default = true;
  }) [ pkg_config_0_3_9_features ];
  libnotify_1_0_3 = { features?(libnotify_1_0_3_features {}) }: libnotify_1_0_3_ {
    dependencies = mapFeatures features ([ gdk_pixbuf_0_3_0 gdk_pixbuf_sys_0_5_0 glib_0_4_1 glib_sys_0_5_0 gobject_sys_0_5_0 libnotify_sys_1_0_2 ]);
  };
  libnotify_1_0_3_features = f: updateFeatures f (rec {
    gdk_pixbuf_0_3_0.default = true;
    gdk_pixbuf_sys_0_5_0.default = true;
    glib_0_4_1.default = true;
    glib_sys_0_5_0.default = true;
    gobject_sys_0_5_0.default = true;
    libnotify_1_0_3.default = (f.libnotify_1_0_3.default or true);
    libnotify_sys_1_0_2.default = true;
  }) [ gdk_pixbuf_0_3_0_features gdk_pixbuf_sys_0_5_0_features glib_0_4_1_features glib_sys_0_5_0_features gobject_sys_0_5_0_features libnotify_sys_1_0_2_features ];
  libnotify_sys_1_0_2 = { features?(libnotify_sys_1_0_2_features {}) }: libnotify_sys_1_0_2_ {
    dependencies = mapFeatures features ([ bitflags_1_0_1 gdk_pixbuf_sys_0_5_0 glib_sys_0_5_0 gobject_sys_0_5_0 libc_0_2_40 ]);
    buildDependencies = mapFeatures features ([ pkg_config_0_3_9 ]);
  };
  libnotify_sys_1_0_2_features = f: updateFeatures f (rec {
    bitflags_1_0_1.default = true;
    gdk_pixbuf_sys_0_5_0.default = true;
    glib_sys_0_5_0.default = true;
    gobject_sys_0_5_0.default = true;
    libc_0_2_40.default = true;
    libnotify_sys_1_0_2.default = (f.libnotify_sys_1_0_2.default or true);
    pkg_config_0_3_9.default = true;
  }) [ bitflags_1_0_1_features gdk_pixbuf_sys_0_5_0_features glib_sys_0_5_0_features gobject_sys_0_5_0_features libc_0_2_40_features pkg_config_0_3_9_features ];
  matches_0_1_6 = { features?(matches_0_1_6_features {}) }: matches_0_1_6_ {};
  matches_0_1_6_features = f: updateFeatures f (rec {
    matches_0_1_6.default = (f.matches_0_1_6.default or true);
  }) [];
  memchr_2_0_1 = { features?(memchr_2_0_1_features {}) }: memchr_2_0_1_ {
    dependencies = mapFeatures features ([ ]
      ++ (if features.memchr_2_0_1.libc or false then [ libc_0_2_40 ] else []));
    features = mkFeatures (features.memchr_2_0_1 or {});
  };
  memchr_2_0_1_features = f: updateFeatures f (rec {
    libc_0_2_40.default = (f.libc_0_2_40.default or false);
    libc_0_2_40.use_std =
      (f.libc_0_2_40.use_std or false) ||
      (memchr_2_0_1.use_std or false) ||
      (f.memchr_2_0_1.use_std or false);
    memchr_2_0_1.default = (f.memchr_2_0_1.default or true);
    memchr_2_0_1.libc =
      (f.memchr_2_0_1.libc or false) ||
      (f.memchr_2_0_1.default or false) ||
      (memchr_2_0_1.default or false) ||
      (f.memchr_2_0_1.use_std or false) ||
      (memchr_2_0_1.use_std or false);
    memchr_2_0_1.use_std =
      (f.memchr_2_0_1.use_std or false) ||
      (f.memchr_2_0_1.default or false) ||
      (memchr_2_0_1.default or false);
  }) [ libc_0_2_40_features ];
  num_integer_0_1_36 = { features?(num_integer_0_1_36_features {}) }: num_integer_0_1_36_ {
    dependencies = mapFeatures features ([ num_traits_0_2_2 ]);
    features = mkFeatures (features.num_integer_0_1_36 or {});
  };
  num_integer_0_1_36_features = f: updateFeatures f (rec {
    num_integer_0_1_36.default = (f.num_integer_0_1_36.default or true);
    num_integer_0_1_36.std =
      (f.num_integer_0_1_36.std or false) ||
      (f.num_integer_0_1_36.default or false) ||
      (num_integer_0_1_36.default or false);
    num_traits_0_2_2.default = (f.num_traits_0_2_2.default or false);
  }) [ num_traits_0_2_2_features ];
  num_traits_0_2_2 = { features?(num_traits_0_2_2_features {}) }: num_traits_0_2_2_ {
    features = mkFeatures (features.num_traits_0_2_2 or {});
  };
  num_traits_0_2_2_features = f: updateFeatures f (rec {
    num_traits_0_2_2.default = (f.num_traits_0_2_2.default or true);
    num_traits_0_2_2.std =
      (f.num_traits_0_2_2.std or false) ||
      (f.num_traits_0_2_2.default or false) ||
      (num_traits_0_2_2.default or false);
  }) [];
  percent_encoding_1_0_1 = { features?(percent_encoding_1_0_1_features {}) }: percent_encoding_1_0_1_ {};
  percent_encoding_1_0_1_features = f: updateFeatures f (rec {
    percent_encoding_1_0_1.default = (f.percent_encoding_1_0_1.default or true);
  }) [];
  pkg_config_0_3_9 = { features?(pkg_config_0_3_9_features {}) }: pkg_config_0_3_9_ {};
  pkg_config_0_3_9_features = f: updateFeatures f (rec {
    pkg_config_0_3_9.default = (f.pkg_config_0_3_9.default or true);
  }) [];
  proc_macro2_0_3_6 = { features?(proc_macro2_0_3_6_features {}) }: proc_macro2_0_3_6_ {
    dependencies = mapFeatures features ([ unicode_xid_0_1_0 ]);
    features = mkFeatures (features.proc_macro2_0_3_6 or {});
  };
  proc_macro2_0_3_6_features = f: updateFeatures f (rec {
    proc_macro2_0_3_6.default = (f.proc_macro2_0_3_6.default or true);
    proc_macro2_0_3_6.proc-macro =
      (f.proc_macro2_0_3_6.proc-macro or false) ||
      (f.proc_macro2_0_3_6.default or false) ||
      (proc_macro2_0_3_6.default or false) ||
      (f.proc_macro2_0_3_6.nightly or false) ||
      (proc_macro2_0_3_6.nightly or false);
    unicode_xid_0_1_0.default = true;
  }) [ unicode_xid_0_1_0_features ];
  pulldown_cmark_0_1_2 = { features?(pulldown_cmark_0_1_2_features {}) }: pulldown_cmark_0_1_2_ {
    dependencies = mapFeatures features ([ bitflags_0_9_1 ]
      ++ (if features.pulldown_cmark_0_1_2.getopts or false then [ getopts_0_2_17 ] else []));
    features = mkFeatures (features.pulldown_cmark_0_1_2 or {});
  };
  pulldown_cmark_0_1_2_features = f: updateFeatures f (rec {
    bitflags_0_9_1.default = true;
    getopts_0_2_17.default = true;
    pulldown_cmark_0_1_2.default = (f.pulldown_cmark_0_1_2.default or true);
    pulldown_cmark_0_1_2.getopts =
      (f.pulldown_cmark_0_1_2.getopts or false) ||
      (f.pulldown_cmark_0_1_2.default or false) ||
      (pulldown_cmark_0_1_2.default or false);
  }) [ bitflags_0_9_1_features getopts_0_2_17_features ];
  quine_mc_cluskey_0_2_4 = { features?(quine_mc_cluskey_0_2_4_features {}) }: quine_mc_cluskey_0_2_4_ {
    dependencies = mapFeatures features ([]);
  };
  quine_mc_cluskey_0_2_4_features = f: updateFeatures f (rec {
    quine_mc_cluskey_0_2_4.default = (f.quine_mc_cluskey_0_2_4.default or true);
  }) [];
  quote_0_5_1 = { features?(quote_0_5_1_features {}) }: quote_0_5_1_ {
    dependencies = mapFeatures features ([ proc_macro2_0_3_6 ]);
    features = mkFeatures (features.quote_0_5_1 or {});
  };
  quote_0_5_1_features = f: updateFeatures f (rec {
    proc_macro2_0_3_6.default = (f.proc_macro2_0_3_6.default or false);
    proc_macro2_0_3_6.proc-macro =
      (f.proc_macro2_0_3_6.proc-macro or false) ||
      (quote_0_5_1.proc-macro or false) ||
      (f.quote_0_5_1.proc-macro or false);
    quote_0_5_1.default = (f.quote_0_5_1.default or true);
    quote_0_5_1.proc-macro =
      (f.quote_0_5_1.proc-macro or false) ||
      (f.quote_0_5_1.default or false) ||
      (quote_0_5_1.default or false);
  }) [ proc_macro2_0_3_6_features ];
  rand_0_4_2 = { features?(rand_0_4_2_features {}) }: rand_0_4_2_ {
    dependencies = (if kernel == "fuchsia" then mapFeatures features ([ fuchsia_zircon_0_3_3 ]) else [])
      ++ (if (kernel == "linux" || kernel == "darwin") then mapFeatures features ([ ]
      ++ (if features.rand_0_4_2.libc or false then [ libc_0_2_40 ] else [])) else [])
      ++ (if kernel == "windows" then mapFeatures features ([ winapi_0_3_4 ]) else []);
    features = mkFeatures (features.rand_0_4_2 or {});
  };
  rand_0_4_2_features = f: updateFeatures f (rec {
    fuchsia_zircon_0_3_3.default = true;
    libc_0_2_40.default = true;
    rand_0_4_2.default = (f.rand_0_4_2.default or true);
    rand_0_4_2.i128_support =
      (f.rand_0_4_2.i128_support or false) ||
      (f.rand_0_4_2.nightly or false) ||
      (rand_0_4_2.nightly or false);
    rand_0_4_2.libc =
      (f.rand_0_4_2.libc or false) ||
      (f.rand_0_4_2.std or false) ||
      (rand_0_4_2.std or false);
    rand_0_4_2.std =
      (f.rand_0_4_2.std or false) ||
      (f.rand_0_4_2.default or false) ||
      (rand_0_4_2.default or false);
    winapi_0_3_4.default = true;
    winapi_0_3_4.minwindef = true;
    winapi_0_3_4.ntsecapi = true;
    winapi_0_3_4.profileapi = true;
    winapi_0_3_4.winnt = true;
  }) [ fuchsia_zircon_0_3_3_features libc_0_2_40_features winapi_0_3_4_features ];
  redox_syscall_0_1_37 = { features?(redox_syscall_0_1_37_features {}) }: redox_syscall_0_1_37_ {};
  redox_syscall_0_1_37_features = f: updateFeatures f (rec {
    redox_syscall_0_1_37.default = (f.redox_syscall_0_1_37.default or true);
  }) [];
  regex_0_2_10 = { features?(regex_0_2_10_features {}) }: regex_0_2_10_ {
    dependencies = mapFeatures features ([ aho_corasick_0_6_4 memchr_2_0_1 regex_syntax_0_5_5 thread_local_0_3_5 utf8_ranges_1_0_0 ]);
    features = mkFeatures (features.regex_0_2_10 or {});
  };
  regex_0_2_10_features = f: updateFeatures f (rec {
    aho_corasick_0_6_4.default = true;
    memchr_2_0_1.default = true;
    regex_0_2_10.default = (f.regex_0_2_10.default or true);
    regex_0_2_10.pattern =
      (f.regex_0_2_10.pattern or false) ||
      (f.regex_0_2_10.unstable or false) ||
      (regex_0_2_10.unstable or false);
    regex_syntax_0_5_5.default = true;
    thread_local_0_3_5.default = true;
    utf8_ranges_1_0_0.default = true;
  }) [ aho_corasick_0_6_4_features memchr_2_0_1_features regex_syntax_0_5_5_features thread_local_0_3_5_features utf8_ranges_1_0_0_features ];
  regex_syntax_0_5_5 = { features?(regex_syntax_0_5_5_features {}) }: regex_syntax_0_5_5_ {
    dependencies = mapFeatures features ([ ucd_util_0_1_1 ]);
  };
  regex_syntax_0_5_5_features = f: updateFeatures f (rec {
    regex_syntax_0_5_5.default = (f.regex_syntax_0_5_5.default or true);
    ucd_util_0_1_1.default = true;
  }) [ ucd_util_0_1_1_features ];
  semver_0_9_0 = { features?(semver_0_9_0_features {}) }: semver_0_9_0_ {
    dependencies = mapFeatures features ([ semver_parser_0_7_0 ]);
    features = mkFeatures (features.semver_0_9_0 or {});
  };
  semver_0_9_0_features = f: updateFeatures f (rec {
    semver_0_9_0.default = (f.semver_0_9_0.default or true);
    semver_0_9_0.serde =
      (f.semver_0_9_0.serde or false) ||
      (f.semver_0_9_0.ci or false) ||
      (semver_0_9_0.ci or false);
    semver_parser_0_7_0.default = true;
  }) [ semver_parser_0_7_0_features ];
  semver_parser_0_7_0 = { features?(semver_parser_0_7_0_features {}) }: semver_parser_0_7_0_ {};
  semver_parser_0_7_0_features = f: updateFeatures f (rec {
    semver_parser_0_7_0.default = (f.semver_parser_0_7_0.default or true);
  }) [];
  serde_1_0_38 = { features?(serde_1_0_38_features {}) }: serde_1_0_38_ {
    dependencies = mapFeatures features ([]);
    features = mkFeatures (features.serde_1_0_38 or {});
  };
  serde_1_0_38_features = f: updateFeatures f (rec {
    serde_1_0_38.default = (f.serde_1_0_38.default or true);
    serde_1_0_38.serde_derive =
      (f.serde_1_0_38.serde_derive or false) ||
      (f.serde_1_0_38.derive or false) ||
      (serde_1_0_38.derive or false) ||
      (f.serde_1_0_38.playground or false) ||
      (serde_1_0_38.playground or false);
    serde_1_0_38.std =
      (f.serde_1_0_38.std or false) ||
      (f.serde_1_0_38.default or false) ||
      (serde_1_0_38.default or false);
    serde_1_0_38.unstable =
      (f.serde_1_0_38.unstable or false) ||
      (f.serde_1_0_38.alloc or false) ||
      (serde_1_0_38.alloc or false);
  }) [];
  serde_derive_1_0_38 = { features?(serde_derive_1_0_38_features {}) }: serde_derive_1_0_38_ {
    dependencies = mapFeatures features ([ proc_macro2_0_3_6 quote_0_5_1 serde_derive_internals_0_23_1 syn_0_13_1 ]);
    features = mkFeatures (features.serde_derive_1_0_38 or {});
  };
  serde_derive_1_0_38_features = f: updateFeatures f (rec {
    proc_macro2_0_3_6.default = true;
    quote_0_5_1.default = true;
    serde_derive_1_0_38.default = (f.serde_derive_1_0_38.default or true);
    serde_derive_internals_0_23_1.default = (f.serde_derive_internals_0_23_1.default or false);
    syn_0_13_1.default = true;
    syn_0_13_1.visit = true;
  }) [ proc_macro2_0_3_6_features quote_0_5_1_features serde_derive_internals_0_23_1_features syn_0_13_1_features ];
  serde_derive_internals_0_23_1 = { features?(serde_derive_internals_0_23_1_features {}) }: serde_derive_internals_0_23_1_ {
    dependencies = mapFeatures features ([ proc_macro2_0_3_6 syn_0_13_1 ]);
  };
  serde_derive_internals_0_23_1_features = f: updateFeatures f (rec {
    proc_macro2_0_3_6.default = true;
    serde_derive_internals_0_23_1.default = (f.serde_derive_internals_0_23_1.default or true);
    syn_0_13_1.clone-impls = true;
    syn_0_13_1.default = (f.syn_0_13_1.default or false);
    syn_0_13_1.derive = true;
    syn_0_13_1.parsing = true;
  }) [ proc_macro2_0_3_6_features syn_0_13_1_features ];
  syn_0_13_1 = { features?(syn_0_13_1_features {}) }: syn_0_13_1_ {
    dependencies = mapFeatures features ([ proc_macro2_0_3_6 unicode_xid_0_1_0 ]
      ++ (if features.syn_0_13_1.quote or false then [ quote_0_5_1 ] else []));
    features = mkFeatures (features.syn_0_13_1 or {});
  };
  syn_0_13_1_features = f: updateFeatures f (rec {
    proc_macro2_0_3_6.default = (f.proc_macro2_0_3_6.default or false);
    proc_macro2_0_3_6.proc-macro =
      (f.proc_macro2_0_3_6.proc-macro or false) ||
      (syn_0_13_1.proc-macro or false) ||
      (f.syn_0_13_1.proc-macro or false);
    quote_0_5_1.default = (f.quote_0_5_1.default or false);
    quote_0_5_1.proc-macro =
      (f.quote_0_5_1.proc-macro or false) ||
      (syn_0_13_1.proc-macro or false) ||
      (f.syn_0_13_1.proc-macro or false);
    syn_0_13_1.clone-impls =
      (f.syn_0_13_1.clone-impls or false) ||
      (f.syn_0_13_1.default or false) ||
      (syn_0_13_1.default or false);
    syn_0_13_1.default = (f.syn_0_13_1.default or true);
    syn_0_13_1.derive =
      (f.syn_0_13_1.derive or false) ||
      (f.syn_0_13_1.default or false) ||
      (syn_0_13_1.default or false);
    syn_0_13_1.parsing =
      (f.syn_0_13_1.parsing or false) ||
      (f.syn_0_13_1.default or false) ||
      (syn_0_13_1.default or false);
    syn_0_13_1.printing =
      (f.syn_0_13_1.printing or false) ||
      (f.syn_0_13_1.default or false) ||
      (syn_0_13_1.default or false);
    syn_0_13_1.proc-macro =
      (f.syn_0_13_1.proc-macro or false) ||
      (f.syn_0_13_1.default or false) ||
      (syn_0_13_1.default or false);
    syn_0_13_1.quote =
      (f.syn_0_13_1.quote or false) ||
      (f.syn_0_13_1.printing or false) ||
      (syn_0_13_1.printing or false);
    unicode_xid_0_1_0.default = true;
  }) [ proc_macro2_0_3_6_features quote_0_5_1_features unicode_xid_0_1_0_features ];
  thread_local_0_3_5 = { features?(thread_local_0_3_5_features {}) }: thread_local_0_3_5_ {
    dependencies = mapFeatures features ([ lazy_static_1_0_0 unreachable_1_0_0 ]);
  };
  thread_local_0_3_5_features = f: updateFeatures f (rec {
    lazy_static_1_0_0.default = true;
    thread_local_0_3_5.default = (f.thread_local_0_3_5.default or true);
    unreachable_1_0_0.default = true;
  }) [ lazy_static_1_0_0_features unreachable_1_0_0_features ];
  time_0_1_39 = { features?(time_0_1_39_features {}) }: time_0_1_39_ {
    dependencies = mapFeatures features ([ libc_0_2_40 ])
      ++ (if kernel == "redox" then mapFeatures features ([ redox_syscall_0_1_37 ]) else [])
      ++ (if kernel == "windows" then mapFeatures features ([ winapi_0_3_4 ]) else []);
  };
  time_0_1_39_features = f: updateFeatures f (rec {
    libc_0_2_40.default = true;
    redox_syscall_0_1_37.default = true;
    time_0_1_39.default = (f.time_0_1_39.default or true);
    winapi_0_3_4.default = true;
    winapi_0_3_4.minwinbase = true;
    winapi_0_3_4.minwindef = true;
    winapi_0_3_4.ntdef = true;
    winapi_0_3_4.profileapi = true;
    winapi_0_3_4.std = true;
    winapi_0_3_4.sysinfoapi = true;
    winapi_0_3_4.timezoneapi = true;
  }) [ libc_0_2_40_features redox_syscall_0_1_37_features winapi_0_3_4_features ];
  toml_0_4_6 = { features?(toml_0_4_6_features {}) }: toml_0_4_6_ {
    dependencies = mapFeatures features ([ serde_1_0_38 ]);
  };
  toml_0_4_6_features = f: updateFeatures f (rec {
    serde_1_0_38.default = true;
    toml_0_4_6.default = (f.toml_0_4_6.default or true);
  }) [ serde_1_0_38_features ];
  ucd_util_0_1_1 = { features?(ucd_util_0_1_1_features {}) }: ucd_util_0_1_1_ {};
  ucd_util_0_1_1_features = f: updateFeatures f (rec {
    ucd_util_0_1_1.default = (f.ucd_util_0_1_1.default or true);
  }) [];
  unicode_bidi_0_3_4 = { features?(unicode_bidi_0_3_4_features {}) }: unicode_bidi_0_3_4_ {
    dependencies = mapFeatures features ([ matches_0_1_6 ]);
    features = mkFeatures (features.unicode_bidi_0_3_4 or {});
  };
  unicode_bidi_0_3_4_features = f: updateFeatures f (rec {
    matches_0_1_6.default = true;
    unicode_bidi_0_3_4.default = (f.unicode_bidi_0_3_4.default or true);
    unicode_bidi_0_3_4.flame =
      (f.unicode_bidi_0_3_4.flame or false) ||
      (f.unicode_bidi_0_3_4.flame_it or false) ||
      (unicode_bidi_0_3_4.flame_it or false);
    unicode_bidi_0_3_4.flamer =
      (f.unicode_bidi_0_3_4.flamer or false) ||
      (f.unicode_bidi_0_3_4.flame_it or false) ||
      (unicode_bidi_0_3_4.flame_it or false);
    unicode_bidi_0_3_4.serde =
      (f.unicode_bidi_0_3_4.serde or false) ||
      (f.unicode_bidi_0_3_4.with_serde or false) ||
      (unicode_bidi_0_3_4.with_serde or false);
  }) [ matches_0_1_6_features ];
  unicode_normalization_0_1_5 = { features?(unicode_normalization_0_1_5_features {}) }: unicode_normalization_0_1_5_ {};
  unicode_normalization_0_1_5_features = f: updateFeatures f (rec {
    unicode_normalization_0_1_5.default = (f.unicode_normalization_0_1_5.default or true);
  }) [];
  unicode_xid_0_1_0 = { features?(unicode_xid_0_1_0_features {}) }: unicode_xid_0_1_0_ {
    features = mkFeatures (features.unicode_xid_0_1_0 or {});
  };
  unicode_xid_0_1_0_features = f: updateFeatures f (rec {
    unicode_xid_0_1_0.default = (f.unicode_xid_0_1_0.default or true);
  }) [];
  unreachable_1_0_0 = { features?(unreachable_1_0_0_features {}) }: unreachable_1_0_0_ {
    dependencies = mapFeatures features ([ void_1_0_2 ]);
  };
  unreachable_1_0_0_features = f: updateFeatures f (rec {
    unreachable_1_0_0.default = (f.unreachable_1_0_0.default or true);
    void_1_0_2.default = (f.void_1_0_2.default or false);
  }) [ void_1_0_2_features ];
  url_1_7_0 = { features?(url_1_7_0_features {}) }: url_1_7_0_ {
    dependencies = mapFeatures features ([ idna_0_1_4 matches_0_1_6 percent_encoding_1_0_1 ]);
    features = mkFeatures (features.url_1_7_0 or {});
  };
  url_1_7_0_features = f: updateFeatures f (rec {
    idna_0_1_4.default = true;
    matches_0_1_6.default = true;
    percent_encoding_1_0_1.default = true;
    url_1_7_0.default = (f.url_1_7_0.default or true);
    url_1_7_0.encoding =
      (f.url_1_7_0.encoding or false) ||
      (f.url_1_7_0.query_encoding or false) ||
      (url_1_7_0.query_encoding or false);
    url_1_7_0.heapsize =
      (f.url_1_7_0.heapsize or false) ||
      (f.url_1_7_0.heap_size or false) ||
      (url_1_7_0.heap_size or false);
  }) [ idna_0_1_4_features matches_0_1_6_features percent_encoding_1_0_1_features ];
  utf8_ranges_1_0_0 = { features?(utf8_ranges_1_0_0_features {}) }: utf8_ranges_1_0_0_ {};
  utf8_ranges_1_0_0_features = f: updateFeatures f (rec {
    utf8_ranges_1_0_0.default = (f.utf8_ranges_1_0_0.default or true);
  }) [];
  uuid_0_6_3 = { features?(uuid_0_6_3_features {}) }: uuid_0_6_3_ {
    dependencies = mapFeatures features ([ cfg_if_0_1_2 ]
      ++ (if features.uuid_0_6_3.rand or false then [ rand_0_4_2 ] else []));
    features = mkFeatures (features.uuid_0_6_3 or {});
  };
  uuid_0_6_3_features = f: updateFeatures f (rec {
    cfg_if_0_1_2.default = true;
    rand_0_4_2.default = true;
    uuid_0_6_3.default = (f.uuid_0_6_3.default or true);
    uuid_0_6_3.md5 =
      (f.uuid_0_6_3.md5 or false) ||
      (f.uuid_0_6_3.v3 or false) ||
      (uuid_0_6_3.v3 or false);
    uuid_0_6_3.rand =
      (f.uuid_0_6_3.rand or false) ||
      (f.uuid_0_6_3.v3 or false) ||
      (uuid_0_6_3.v3 or false) ||
      (f.uuid_0_6_3.v4 or false) ||
      (uuid_0_6_3.v4 or false) ||
      (f.uuid_0_6_3.v5 or false) ||
      (uuid_0_6_3.v5 or false);
    uuid_0_6_3.serde =
      (f.uuid_0_6_3.serde or false) ||
      (f.uuid_0_6_3.playground or false) ||
      (uuid_0_6_3.playground or false);
    uuid_0_6_3.sha1 =
      (f.uuid_0_6_3.sha1 or false) ||
      (f.uuid_0_6_3.v5 or false) ||
      (uuid_0_6_3.v5 or false);
    uuid_0_6_3.std =
      (f.uuid_0_6_3.std or false) ||
      (f.uuid_0_6_3.default or false) ||
      (uuid_0_6_3.default or false) ||
      (f.uuid_0_6_3.use_std or false) ||
      (uuid_0_6_3.use_std or false);
    uuid_0_6_3.v1 =
      (f.uuid_0_6_3.v1 or false) ||
      (f.uuid_0_6_3.playground or false) ||
      (uuid_0_6_3.playground or false);
    uuid_0_6_3.v3 =
      (f.uuid_0_6_3.v3 or false) ||
      (f.uuid_0_6_3.playground or false) ||
      (uuid_0_6_3.playground or false);
    uuid_0_6_3.v4 =
      (f.uuid_0_6_3.v4 or false) ||
      (f.uuid_0_6_3.playground or false) ||
      (uuid_0_6_3.playground or false);
    uuid_0_6_3.v5 =
      (f.uuid_0_6_3.v5 or false) ||
      (f.uuid_0_6_3.playground or false) ||
      (uuid_0_6_3.playground or false);
  }) [ cfg_if_0_1_2_features rand_0_4_2_features ];
  void_1_0_2 = { features?(void_1_0_2_features {}) }: void_1_0_2_ {
    features = mkFeatures (features.void_1_0_2 or {});
  };
  void_1_0_2_features = f: updateFeatures f (rec {
    void_1_0_2.default = (f.void_1_0_2.default or true);
    void_1_0_2.std =
      (f.void_1_0_2.std or false) ||
      (f.void_1_0_2.default or false) ||
      (void_1_0_2.default or false);
  }) [];
  winapi_0_3_4 = { features?(winapi_0_3_4_features {}) }: winapi_0_3_4_ {
    dependencies = (if kernel == "i686-pc-windows-gnu" then mapFeatures features ([ winapi_i686_pc_windows_gnu_0_4_0 ]) else [])
      ++ (if kernel == "x86_64-pc-windows-gnu" then mapFeatures features ([ winapi_x86_64_pc_windows_gnu_0_4_0 ]) else []);
    features = mkFeatures (features.winapi_0_3_4 or {});
  };
  winapi_0_3_4_features = f: updateFeatures f (rec {
    winapi_0_3_4.default = (f.winapi_0_3_4.default or true);
    winapi_i686_pc_windows_gnu_0_4_0.default = true;
    winapi_x86_64_pc_windows_gnu_0_4_0.default = true;
  }) [ winapi_i686_pc_windows_gnu_0_4_0_features winapi_x86_64_pc_windows_gnu_0_4_0_features ];
  winapi_i686_pc_windows_gnu_0_4_0 = { features?(winapi_i686_pc_windows_gnu_0_4_0_features {}) }: winapi_i686_pc_windows_gnu_0_4_0_ {};
  winapi_i686_pc_windows_gnu_0_4_0_features = f: updateFeatures f (rec {
    winapi_i686_pc_windows_gnu_0_4_0.default = (f.winapi_i686_pc_windows_gnu_0_4_0.default or true);
  }) [];
  winapi_x86_64_pc_windows_gnu_0_4_0 = { features?(winapi_x86_64_pc_windows_gnu_0_4_0_features {}) }: winapi_x86_64_pc_windows_gnu_0_4_0_ {};
  winapi_x86_64_pc_windows_gnu_0_4_0_features = f: updateFeatures f (rec {
    winapi_x86_64_pc_windows_gnu_0_4_0.default = (f.winapi_x86_64_pc_windows_gnu_0_4_0.default or true);
  }) [];
}
